name: sandbox_dart
version: 0.0.1
description: Sandbox project for learning Dart
homepage: https://github.com/dburyak/sandbox-dart
repository: https://github.com/dburyak/sandbox-dart

platforms:
  linux:
  web:

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  http: ^1.1.1
  args: ^2.3.1
  logging: ^1.1.0
  git: ^2.2.0
  path: ^1.8.3
  collection: ^1.17.0
  intl: ^0.19.0

  # json_serializable works in combination with json_annotation
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.22.1
  mockito: ^5.3.2
  build_runner: ^2.3.3
  build_web_compilers: ^4.0.7

  # json_serializable works in combination with json_annotation
  json_serializable: ^6.7.1

publish_to: none
