name: sandbox_dart
version: 0.0.1
description: Sandbox project for learning Dart
homepage: https://github.com/dburyak/sandbox-dart
repository: https://github.com/dburyak/sandbox-dart

platforms:
  linux:
  web:

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  mockito: ^5.3.2

publish_to: none
